version: "3.3"
services:
    openssh-build:
        restart: "no"
        image: budney/openssh-build
        build:
            dockerfile: ./Dockerfile
            context: ./
        volumes:
            - ./packages:/packages
